[project]
name = "resolvor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.2.0",
    "langgraph>=1.0.5",
]

[dependency-groups]
dev = [
    "datamodel-code-generator>=0.49.0",
]
